language: cpp

os:
  - linux
  - osx

dist: trusty

compiler:
  - clang
  - gcc

env:
  # - CONFIG=Release
  - CONFIG=Debug

branches:
  only:
    - dev

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - ./scripts/clean.sh
  - ./scripts/build.sh
  - ./scripts/test.sh